# Generated by Django 4.2.1 on 2023-05-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
